In [423]:
import pandas as pd
import numpy as np
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


data= pd.read_csv('car.data')

In [424]:
data.head()

buying  maint doors persons lug_boot Safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [425]:
#Data Labelling
X = data[['buying','maint','Safety']].values

In [426]:
y=data[['class']]

In [427]:
print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [428]:
#converting the data
#Label Encoding
le = LabelEncoder()

In [429]:
for i in range(len(X[0])):
    X[:, i]= le.fit_transform(X[:, i])

In [430]:
    print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [431]:


label_mapping={'unacc':0,'acc':1,'good':2,'vgood':3}
y['class'] = y['class'].map(label_mapping)
y=np.array(y)

C:\Users\dhina\AppData\Local\Temp/ipykernel_1412/1850955083.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [432]:
print(y)    

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


In [433]:
#creating the model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

In [434]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)

In [435]:
print(X_test)

[[0 3 2]
 [2 3 2]
 [2 3 0]
 ...
 [2 2 0]
 [3 0 1]
 [2 1 2]]


In [436]:
np.ravel(y)
knn.fit(X,y)

C:\Users\dhina\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [437]:
#x_test is the value we are going to find

prediction = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, prediction)

In [438]:
print("Prediction", prediction)
print("accuracy", accuracy)


Prediction [0 0 1 1 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 3 0 0 3 0 0 1 0 0 1 0
 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 1 0 0 0 1
 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 1 0 0 0 2 3 0 0 2 0 1 3 0 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 2 0 0 0 0 0 2 0 1 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 0 1 2 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 2 0 0 0 1 0 0 0 0 3 0
 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 3 1 0 0 0 0 0 2 0 2 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 1 0 0 1 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 1 0 0 2 1 0 0 0 2 0 1 0 0 0 0 1 1 1 0 0
 1 0 1 3 0 0 1 0 0 0 0 0 0]
accuracy 0.7803468208092486


In [439]:
a = int(input())
print("Actual Value: ", y[a])
print("Predicted Value: ", knn.predict(X)[a])

Actual Value:  [0]
Predicted Value:  0


In [440]:
from sklearn.metrics import confusion_matrix

In [442]:
cm = confusion_matrix(y_test, prediction)

In [443]:
print(cm)

[[215  19   4   6]
 [ 27  48   4   0]
 [  7   0   5   3]
 [  6   0   0   2]]
